esphome:
  name: test
  friendly_name: test

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "VIzE/5a2gPxZAI6ssFMcSUGMJUkrbFXCWbKYxQqfR+0="

ota:
  - platform: esphome
    password: "aaf34e2d4d50eee5a23fa0a3bdee586a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "7yD3hXt2vwaP"

captive_portal:

external_components:
  - source:
      type: local
      path: ../components
    components: [ehmtxv2]

sensor:
  - platform: uptime
    name: "Sensor ${name} Uptime"

substitutions:
  name: LED Matrix
  ledpin: GPIO02 #D4

light:
  - platform: neopixelbus
    id: ehmtx_light
    type: GRB
    variant: WS2812
    pin: $ledpin
    num_leds: 256
    color_correct: [30%, 30%, 30%]
    name: "$name Light"
    restore_mode: ALWAYS_OFF
display:
  - platform: addressable_light
    id: ehmtx_display
    addressable_light_id: ehmtx_light
    width: 32
    height: 8
    pixel_mapper: |-
      if (x % 2 == 0) {
        return (x * 8) + y;
      }
      return (x * 8) + (7 - y);
    rotation: 0°
    update_interval: 16ms
    auto_clear_enabled: true
    lambda: |-
      id(rgb8x32)->tick();
      id(rgb8x32)->draw();

time:
  - platform: homeassistant
    id: ehmtx_time
    timezone: "Europe/Berlin"

ehmtxv2:
  id: rgb8x32
  show_seconds: true
  show_dow: false
  rainbow_interval: 32
  matrix_component: ehmtx_display
  time_component: ehmtx_time
  icons2html: true
  default_font_id: default_font
  special_font_id: default_font
  special_font_yoffset: 8
  default_font_yoffset: 8
  #night_mode_screens: 5
  icons:
    - lameid: 19109
      id: coffee
    - lameid: 58
      id: tree
    - lameid: 794
      id: heart

animation:
  - id: animation_black
    file: "1pixel.gif"

image:
  - id: image_black
    file: "1pixel.gif"

font:
  - file: EHMTXv2.ttf
    size: 16
    id: default_font
    glyphs: |-
      !?"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnÖÄÜöäüopqrstuvwxyz@<>ß€/
