name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-stable:
    name: Build stable ${{ matrix.firmware.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        firmware:
          - file: tests/ulanzi-test.yaml
            name: Ulanzi-Easy
            manifest_filename: ulanzi-test-manifest.json
      fail-fast: false
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.3.0
      - name: Build firmware
        uses: esphome/build-action@v3
        id: esphome-build
        with:
          yaml_file: ${{ matrix.firmware.file }}
          version: latest
